# Generated by Django 5.1.4 on 2025-01-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0002_superuser_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Ustoz'), ('parent', 'Ota-Ona'), ('student', "O'quvchi")], default='student', max_length=10),
        ),
        migrations.DeleteModel(
            name='Superuser',
        ),
    ]
