# Generated by Django 5.1.4 on 2025-01-02 03:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0004_subject_user_created_user_updated_group_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='lesson_time',
            new_name='lesson_end_time',
        ),
        migrations.AddField(
            model_name='group',
            name='lesson_start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
