# Generated by Django 5.1.4 on 2025-01-03 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0007_user_student_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='student_group',
            new_name='student_groups',
        ),
    ]
